env:
    browser: true
    es2021: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
overrides: [ ]
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: latest
plugins:
    - '@typescript-eslint'
ignorePatterns:
    - src/commands/sample.ts
    - test/test-base-utils.spec.ts
    - test/*
rules:
    no-non-null-assertion: 0
    "@typescript-eslint/no-unused-vars": 0
    "@typescript-eslint/no-non-null-assertion": 0
    "@typescript-eslint/no-empty-interface": 0
    "@eslint-disable-next-line @typescript-eslint/no-loss-of-precision": 0
    "@typescript-eslint/no-explicit-any": 0
    "@typescript-eslint/ban-ts-comment": 0
    "@typescript-eslint/no-var-requires": 0
    "@typescript-eslint/no-empty-function": 0
    "@typescript-eslint/no-non-null-asserted-optional-chain": 0
    no-await-in-loop: off
    no-self-compare: error
    no-template-curly-in-string: error # This rule should not be used in ES3/5 environments.
    no-use-before-define: off
    no-constant-condition: off
    no-useless-catch: off
#    arrow-body-style:
#        - error
#        - always
    block-scoped-var: error
    camelcase:
        - error
        -   properties: always
            ignoreGlobals: false
    capitalized-comments:
        - off
        - always
        -
            ignoreInlineComments: true
            ignoreConsecutiveComments: true
#            ignorePattern: "default"
    complexity:
        - error
        - 20
    curly:
        - error
        - multi
    default-case:
        - off
    default-case-last: error
    default-param-last: error
    dot-notation: error
    prefer-rest-params: off
    eqeqeq:
        - off
        - smart
    guard-for-in: error
    id-length:
        - error
        -   min: 1
            max: 35
            properties: always
    id-match:
        - error
        - "^[a-zA-z]+[a-zA-Z\\d]*$"
        -   classFields: true
            properties: true
            onlyDeclarations: true
    max-depth:
        - error
        - 4
    max-lines:
        - error
        -   max: 500
            skipComments: true
            skipBlankLines: true
    max-lines-per-function:
        - error
        -   max: 100
            skipComments: true
            skipBlankLines: true
    max-params:
        - error
        - 5
#    no-console: error # Todo: zapnout pro produkci, vytvořit vlastní třídu Console
    no-else-return:
        - error
        - allowElseIf: false
    no-empty:
        - error
        - allowEmptyCatch: true
    no-useless-escape: off
    no-empty-function:
        - off
        - allow:
            - constructors
    no-empty-static-block:
        - error
    no-eq-null: error
    no-extra-label: warn
    no-extra-semi: error
    no-floating-decimal: error
    no-implicit-coercion:
        - error
        -   boolean: true
            number: true
            string: false
    no-mixed-operators:
        - error
        - groups:
              - ["&&", "||"]
    no-multi-assign: error
    no-multi-str: error
    no-negated-condition: off
    no-nested-ternary: error
    no-octal: error
    no-regex-spaces: error
    no-return-assign: error
    no-script-url: error
    no-ternary: off
    no-var: error
    no-warning-comments:
        - error
        - terms:
            - fixme
            - todo
    operator-assignment:
        - error
        - always
    prefer-const: error
    spaced-comment:
        - off # error
        - always
        -   line:
                exceptions: ["-", "-+", "=", "*", "region", "endregion"]
            block:
                exceptions: ["-", "-+", "=", "*", "region", "endregion"]
    strict:
        - error
        - global
    yoda:
        - error
        - never
    sort-imports: off

    # Code formatting
    array-bracket-newline:
        - error
        -   multiline: true
            minItems: 4 # 2 - 3
    array-bracket-spacing:
        - error
        - never
    array-element-newline:
        - error
        -   multiline: true
            minItems: 2 # 2 - 3
    arrow-spacing:
        - error
        -   before: true
            after: true
    block-spacing:
        - error
        - always
    brace-style:
        - error
        - 1tbs
        - allowSingleLine: true
    comma-dangle:
        - error
        -   arrays: always-multiline
            objects: always
            imports: only-multiline
            exports: always
            functions: always-multiline
    comma-spacing:
        - error
        -   before: false
            after: true
    comma-style:
        - error
        - last
    computed-property-spacing:
        - error
        - never
    dot-location:
        - error
        - property
    eol-last:
        - error
        - always
    func-call-spacing:
        - error
        - never
    implicit-arrow-linebreak:
        - error
        - beside
    indent:
        - error
        - 4
        -   SwitchCase: 1
            FunctionDeclaration:
                  body: 1
                  parameters: 3
            ignoredNodes:
                - PropertyDefinition
    key-spacing:
        - error
        -   beforeColon: false
            afterColon: true
            mode: strict
#            align: colon
    keyword-spacing:
        - error
        -
            before: true
            after: true
    linebreak-style:
        - error
        - unix
    lines-between-class-members:
        - off # error
        - always
    max-len:
        - error
        -
            code: 160 # Todo: změnit
    newline-per-chained-call:
        - error
        - ignoreChainWithDepth: 2 # !Todo: asi?
    no-mixed-spaces-and-tabs: error
    no-multi-spaces:
        - error
        -   ignoreEOLComments: true # https://eslint.org/docs/latest/rules/no-multi-spaces
    no-multiple-empty-lines:
        - error
        -   max: 2
    no-tabs:
        - error
        - allowIndentationTabs: false
    no-trailing-spaces:
        - error
        -   ignoreComments: true
            skipBlankLines: false
    no-whitespace-before-property:
        - error
    object-curly-newline:
        - error
        -   ImportDeclaration:
                minProperties: 4
            ObjectExpression:
                minProperties: 2
    object-curly-spacing:
        - error
        - always
    operator-linebreak: off
    padded-blocks: off
    padding-line-between-statements:
        - error
#        -   blankLine: always
#            prev: "*"
#            next: "return"
#        -   blankLine: always
#            prev: ["const", "let", "var"]
#            next: "*"
#        -   blankLine: "any"
#            prev: ["const", "let", "var"]
#            next: ["const", "let", "var"]
        -   blankLine: "always"
            prev: "directive"
            next: "*"
        -   blankLine: "any"
            prev: "directive"
            next: "directive"
    quotes:
        - error
        - double
    rest-spread-spacing:
        - error
        - never
    semi:
        - error
        - always
    semi-spacing:
        - error
        - before: false
          after: true
    semi-style:
        - error
        - last
    space-before-blocks:
        - error
        - always
    space-before-function-paren:
        - error
        - named: never
          anonymous: never
          asyncArrow: always
    space-in-parens: error
    space-infix-ops: error
    space-unary-ops:
        - error
        - words: true
          nonwords: false
    switch-colon-spacing:
        - error
        - before: false
          after: true
    template-curly-spacing:
        - error
        - always
    template-tag-spacing:
        - error
        - always
    wrap-regex: error



# https://eslint.org/docs/latest/rules/func-style
# https://eslint.org/docs/latest/rules/multiline-comment-style
# https://eslint.org/docs/latest/rules/no-console#when-not-to-use-it
# https://eslint.org/docs/latest/rules/no-continue
# https://eslint.org/docs/latest/rules/no-param-reassign
# https://eslint.org/docs/latest/rules/no-warning-comments
# https://eslint.org/docs/latest/rules/sort-imports
# https://eslint.org/docs/latest/rules/strict
# https://eslint.org/docs/latest/rules/arrow-parens
# https://eslint.org/docs/latest/rules/function-paren-newline
# https://eslint.org/docs/latest/rules/multiline-ternary
# https://eslint.org/docs/latest/rules/nonblock-statement-body-position
# https://eslint.org/docs/latest/rules/object-property-newline
#


# Shorthand | Separate
#-----------|------------
# x += y    | x = x + y
# x -= y    | x = x - y
# x *= y    | x = x * y
# x /= y    | x = x / y
# x %= y    | x = x % y
# x **= y   | x = x ** y
# x <<= y   | x = x << y
# x >>= y   | x = x >> y
# x >>>= y  | x = x >>> y
# x &= y    | x = x & y
# x ^= y    | x = x ^ y
# x |= y    | x = x | y
